// Configuración automática de redirects
// Generado por scripts/generate-redirects.js

export const REDIRECTS_MAP = {
  "15-ideas-originales-a-buen-precio-para-regalar-esta-primavera": "recomendaciones",
  "5-chanclas-para-hombre-para-disfrutar-del-verano": "recomendaciones",
  "adios-a-la-celulitis-descubre-los-secretos-para-combatirla": "recomendaciones",
  "aesthetic": "mujer",
  "amarillo-como-llevarlo-con-estilo": "mujer",
  "blanco-y-beige-como-combinarlos": "mujer",
  "botines-de-mujer-como-combinar-unos-botines-con-estilo": "recomendaciones",
  "boxers-masculinos": "recomendaciones",
  "cara-cuadrada": "mujer",
  "cara-diamante-hombre": "hombre",
  "coleccion-de-relojes-precision-y-estilo-en-bizzarro": "recomendaciones",
  "color-de-unas-para-vestido-verde": "mujer",
  "combinar-pantalon-marron-hombre": "hombre",
  "combinar-zapatos-marrones": "hombre",
  "como-combinar-pantalon-azul": "zapatos",
  "como-combinar-pantalon-beige": "mujer",
  "como-combinar-pantalon-blanco": "mujer",
  "como-combinar-pantalon-celeste": "mujer",
  "como-combinar-pantalon-negro": "mujer",
  "como-combinar-pantalon-verde": "mujer",
  "como-elegir-un-centro-ideal-para-tus-unas-de-gel": "recomendaciones",
  "como-evitar-que-el-perfume-manche-la-ropa": "recomendaciones",
  "como-vestir-de-forma-elegante-y-sostenible": "recomendaciones",
  "como-vestir-para-una-boda-sin-traje": "hombre",
  "como-vestir-para-una-boda": "mujer",
  "como-vestirse-de-azul-mujer": "mujer",
  "cortes-y-peinados-de-hombre": "hombre",
  "cosmetica-ecologica-coherente": "recomendaciones",
  "cuales-son-los-tipos-de-plata-que-existen": "recomendaciones",
  "descubre-como-funciona-efimero-club-bolsos-de-lujo-por-suscripcion": "recomendaciones",
  "disenadores-de-moda-milan": "mujer",
  "esclavas-de-oro-tradicion-y-estilo-que-perduran": "recomendaciones",
  "faldas-de-los-90-como-llevarlas-hoy": "mujer",
  "la-moda-sostenible-esta-en-pleno-auge": "recomendaciones",
  "la-rutina-de-limpieza-facial-que-mas-notara-tu-rostro": "recomendaciones",
  "las-zapatillas-de-las-que-todo-el-mundo-habla-cetti": "recomendaciones",
  "look-de-invierno-de-mujer": "mujer",
  "look-para-ano-nuevo": "mujer",
  "looks-bautizo": "mujer",
  "looks-con-bermudas-hombre": "hombre",
  "looks-para-embarazadas": "mujer",
  "los-tratamientos-de-estetica-mas-habituales-en-primavera": "recomendaciones",
  "manual-de-estilo-el-vestido-midi-cortefiel": "recomendaciones",
  "marcas-de-ropa-interior-de-mujer": "mujer",
  "metodo-curly-que-es": "recomendaciones",
  "mipelazo-com": "recomendaciones",
  "outfit-hombre": "hombre",
  "outfit-oficina-hombre": "hombre",
  "outfit-pantalon-gris": "mujer",
  "outfit-primavera-mujer": "mujer",
  "outfit-verano-hombre": "hombre",
  "outfits-con-zapatillas": "mujer",
  "pantalon-engomado": "mujer",
  "pantalones-capri-como-combinarlos": "mujer",
  "perfume-carolina-herrera": "mujer",
  "perfumes-nicho-descubre-la-esencia-exclusiva-de-la-elegancia": "recomendaciones",
  "piel-seca-en-invierno-esto-es-lo-que-hay-que-hacer-ef-bf-bc": "recomendaciones",
  "prendas-basicas-para-mujer": "mujer",
  "psicologia-de-la-ropa": "mujer",
  "que-tipo-de-anteojos-de-sol-usar-segun-rostro": "mujer",
  "recomendaciones-de-moda-para-la-noche-de-halloween": "recomendaciones",
  "ropa-deportiva-sostenible-un-compromiso-con-la-moda-y-el-planeta": "recomendaciones",
  "rostro-ovalado": "mujer",
  "rostro-redondo-mujer": "mujer",
  "sandalias-bio-comodidad-y-estilo-de-la-mano": "recomendaciones",
  "serum-minimizador-de-poros": "recomendaciones",
  "smart-casual-hombre": "hombre",
  "tatuajes-para-mujer-en-el-brazo": "mujer",
  "tatuajes-para-mujeres-en-la-espalda": "mujer",
  "tipos-de-cuerpo-de-mujer": "mujer",
  "tipos-de-rostros-de-hombre": "hombre",
  "tipos-de-zapatos-para-mujeres-bajitas": "mujer",
  "tips-de-moda-para-mujeres-gorditas": "mujer",
  "traje-de-bano-mujer": "mujer",
  "unas-para-vestido-negro": "mujer",
  "vender-cosas-que-no-utilizas-o-ya-no-te-pones-y-ganar-dinero": "recomendaciones",
  "zapatillas-de-casa-que-son": "recomendaciones",
  "zapatillas-sin-cordones-como-combinar-sin-morir-en-el-intento": "recomendaciones",
  "zapatos-para-jeans-mujer": "mujer",
  "zapatos-para-outfit-oficina-hombre": "hombre",
  "zapatos-para-vestidos": "mujer",
  "zapatos-y-accesorios-para-vestido-verde": "mujer"
};

export function getRedirectPath(slug) {
  const category = REDIRECTS_MAP[slug];
  return category ? `/${category}/${slug}` : null;
}
